Add typescript support and define `Proptypes` to each component
Developer-DAO/developer-dao pull request #100
Opened 2021-09-21 07:09 UTC by Nazeeh21

This PR fixes #84.

@with-heart In case of any of the changes or improvements required do let me know.

2021-09-21 12:47 UTC, with-heart commented
Since we have TypeScript now, we can actually remove `prop-types` and `Component.propTypes` definitions.

2021-09-21 12:59 UTC, with-heart requested changes
Looks really good and I'm glad to have TS now! Just a few notes and requested changes.

2021-09-21 12:59 UTC, with-heart commented on src/components/Icons/discord.tsx
> +function IconDiscord({ className }: Props) {
I'm fine with leaving it the way it is, but I think we'd also be fine to establish a pattern of inlining non-exported prop types.

```suggestion
function IconDiscord({ className }: {className?: string}) {
```

2021-09-21 12:59 UTC, with-heart commented on src/components/Icons/github.tsx
>   */
We can remove this since we're attaching props directly to the component.

2021-09-21 12:59 UTC, with-heart commented on src/components/Logo/index.tsx
>   */
We can remove this

2021-09-21 12:59 UTC, with-heart commented on src/components/Search/Dev/DevName.tsx
> +      disabled={true}
I know you didn't add this prop, but could you change this to `isDisabled`? `isDisabled` is the prop Chakra uses to control the disabled state of a button.

2021-09-21 12:59 UTC, with-heart commented on tsconfig.json
> +    "next.config.js"
Duplicate lines

```suggestion
    "next.config.js",
```

2021-09-21 12:59 UTC, with-heart commented on tsconfig.json
> +    "strict": false,
What happens if we change this to `true`? I'd prefer we start with it enabled if possible.

2021-09-21 13:04 UTC, with-heart commented
Could you add a `type-check` script to `package.json`?

```json
"type-check": "tsc --noEmit"
```

We can add that to our PR Actions at a later step, but for now that would give us a script to run that validates that `tsc` finds no type errors.

2021-09-21 13:28 UTC, with-heart commented on src/pages/_app.tsx
> +}) => (
Next.js has a type for this:

```suggestion
const App = ({
  Component,
  pageProps,
}: AppProps) => (
```

Imported using `import type { AppProps } from 'next/app'`

2021-09-21 13:39 UTC, Nazeeh21 commented
I have updated the changes and fix typescript types in other files as well.

2021-09-21 14:41 UTC, Nazeeh21 commented
I am not getting an option to fetch the Upstream branch on my repo

![image](https://user-images.githubusercontent.com/56908732/134192131-6926f5cb-b072-4e5c-8030-929294f19594.png)

2021-09-21 14:54 UTC, Nazeeh21 commented
I have updated the PR by merging the `Developer-dao:main` branch and resolving merge conlicts.

2021-09-22 15:01 UTC, Nazeeh21 commented
I have updated the PR by fetching the upstream branch and resolving merge conflicts.

2021-09-22 17:16 UTC, merged