Add github usernames besides projects on /projects route
Developer-DAO/developer-dao pull request #119
Opened 2021-09-26 08:58 UTC by Nazeeh21

### What does it do?
Add GitHub usernames of the project who worked on besides the project name on `/projects` route and add a translation for `by` in `en` language.

### Any helpful background information?
--

### Any new dependencies? Why were they added?
--

### Relevant screenshots/gifs
![image](https://user-images.githubusercontent.com/56908732/134800942-b36de0ae-19aa-4011-913b-d4dc8483c11f.png)

### Does it close any issues?

Closes #113

2021-09-26 09:02 UTC, Nazeeh21 commented
For now, I have added placeholder names besides the project. I don't know the project owners so I haven't added that. If you provide me their names, I'll update the PR with their names and GitHub links.

2021-09-27 05:37 UTC, codingwithmanny commented on src/pages/projects.tsx
> +                <Text>Filipe Oliveira</Text>
I think this is @Ibby-devv (discord: IbbyDev#8201)
Might need to confirm with them.

2021-09-27 10:14 UTC, Nazeeh21 commented on src/pages/projects.tsx
> +                <Text>Filipe Oliveira</Text>
Okay! I'll update them as soon as @Ibby-devv approves it.

2021-09-27 14:50 UTC, with-heart commented on src/pages/projects.tsx
> +                <Text>Filipe Oliveira</Text>
I think you're good to make the change. Very confident that @ibby-dev is the correct profile.

2021-09-27 15:30 UTC, with-heart requested changes
Looks good! Just one requested change to simplify the list elements structure

2021-09-27 15:30 UTC, with-heart commented on src/pages/projects.tsx
> +              </Flex>
Shouldn't need to use `Flex` here

```tsx
<ListItem>
  <Link>Developer DAO</Link> - {t('by')} <Link>fmoliviera</Link>
</ListItem>
```

If we don't use `Box` or `Text`, there's nothing forcing the lines to break

2021-09-27 16:11 UTC, Nazeeh21 commented on src/pages/projects.tsx
> +              </Flex>
I have made the changes and also updated the owner name for *DDAO Token Search*.

2021-09-27 16:15 UTC, with-heart approved these changes
I think we're good to go!

2021-09-27 16:16 UTC, codingwithmanny approved these changes
LGTM

2021-09-27 16:16 UTC, merged