Updated README.md
Developer-DAO/developer-dao pull request #13
Opened 2021-09-09 21:02 UTC by kempsterrrr

First draft of updated `README.md`. Took inspiration from a few popular projects out there but totally open to change.

Wording for explain developerdao is largely taken from posts by Nader and others in our discord.

Appreciate suggestions and feedback.

2021-09-09 23:28 UTC, xdrdak commented on README.md
> +That said, ther is a limited supply of NFT's that can be created.
```suggestion
That said, there is a limited supply of NFT's that can be created.
```

2021-09-09 23:29 UTC, xdrdak commented on README.md
> +1. Clonse this repo with git
```suggestion
1. Clone this repo with git
```

2021-09-09 23:30 UTC, xdrdak commented on README.md
> +2. install dependencies by running `yarn` within the directory you clone the project (probably `developer-dao`)
We can safely omit the rest as it's kinda implied
```suggestion
2. Install the dependencies by running `yarn` 
```

2021-09-10 11:59 UTC, kempsterrrr commented
Fixed typo's, thanks @xdrdak

2021-09-10 15:57 UTC, with-heart approved these changes
This is such a great starting point! Just a few random nitpicks and suggestions but I think this is basically good to go!

2021-09-10 15:57 UTC, with-heart commented on README.md
> +[![Chat on Discord](https://img.shields.io/badge/chat-Discord-7289DA?logo=discord)](https://discord.com/invite/ZHZup79J) [![Follow on Twitter](https://img.shields.io/badge/social-Twitter-1DA1F2?logo=
I wonder if we have enough members yet to qualify for a custom Discord invite URL. I'm not even sure who to ask!

2021-09-10 15:57 UTC, with-heart commented on README.md
> +This is the code DeveloperDAO's public facing - https://www.developerdoa.com.
```suggestion
This is the code for the [public DeveloperDAO site](https://developerdao.com/).
```

I think this reads a little better. URL had a small typo too

2021-09-10 15:57 UTC, with-heart commented on README.md
> +At the moment it allows members to view their genesis NFT by entering in it's ID. As the community takes shape we will decide what this website becomes and build it as a collective.
```suggestion
At the moment it allows members to view their genesis NFT by entering in its ID. As the community takes shape we will decide what this website becomes and build it as a collective.
```

2021-09-10 15:57 UTC, with-heart commented on README.md
> +DAO stands for Decentalized autonomous organisation. That is a group of people with shared goals/mission that are governed by an agreed set of rules coded into a smart contract(s) on a blockchain.
```suggestion
DAO stands for **D**ecentalized **A**utonomous **O**rganisation. That is a group of people with shared goals/mission that are governed by an agreed set of rules coded into a smart contract(s) on a blockchain.
```

2021-09-10 15:57 UTC, with-heart commented on README.md
> +https://coopahtroopa.mirror.xyz/gWY6Kfebs9wHdfoZZswfiLTBVzfKiyFaIwNf2q8JpgI
```suggestion
If you want to learn more about DAOs, check out Cooper Turley's blog at https://alias.co/coopahtroopa/essays, mainly ["The Rise of Micro-Economies"](https://coopahtroopa.mirror.xyz/gWY6Kfebs9wHdfoZZswfiLTBVzfKiyFaIwNf2q8JpgI).
```

2021-09-10 15:57 UTC, with-heart commented on README.md
> +The project was started as an experiment by [Nader Dabit](https://twitter.com/dabit3) to see what can be achieved when we bring together talented and likeminded people who are interested in learning
```suggestion
The project was started as an experiment by [Nader Dabit](https://twitter.com/dabit3) to see what can be achieved when we bring together talented and like-minded people who are interested in learning about and building on Web3.
```

2021-09-10 15:57 UTC, with-heart commented on README.md
> +As stated on : "Developers around the world are tired of working and contributing their time and effort to enrich the top 1%. Join the movement that is community owned, building the future from the b
Where was this stated?

2021-09-10 15:57 UTC, with-heart commented on README.md
> +The DAO operates inside our [discord sever](https://twitter.com/dabit3). To gain access to this server you need to own a [Devs for Revolution](https://opensea.io/collection/devs-for-revolution) NFT.
```suggestion
The DAO operates inside our [discord sever](https://twitter.com/dabit3). To gain access to this server you need to own a [Devs for Revolution](https://opensea.io/collection/devs-for-revolution) NFT. The contract for purchasing one [can be found on etherscan.io](https://etherscan.io/token/0x25ed58c027921e14d86380ea2646e3a1b5c55a8b). If you're not sure how to purchase an NFT, [check out this how-to article](https://jonkuperman.com/how-to-join-developer-dao/) by @jkup. 
```

Should we refer to it as minting rather than purchasing? Not sure what the exact terminology is here.

2021-09-10 15:57 UTC, with-heart commented on README.md
> +That said, there is a limited supply of NFT's that can be created.
This is probably a great place to link to one of those tools that shows the remaining available NFTs. Not sure which one we should link to though, I think I've seen a few.

2021-09-10 15:57 UTC, with-heart commented on README.md
```suggestion

[Discord]: https://discord.gg/ZHZup79J
```

Allows us to define the link in a single place and reference it throughout the doc. If we change it in the future, we only need to change this one!

2021-09-10 15:57 UTC, with-heart commented on README.md
> +If you get stuck please reach out on our [discord](https://discord.gg/ZHZup79J) and we'd be happy to help.
```suggestion
If you get stuck please reach out on our [Discord] and we'd be happy to help.
```

2021-09-10 15:57 UTC, with-heart commented on README.md
> +The DAO operates inside our [discord sever](https://twitter.com/dabit3). To gain access to this server you need to own a [Devs for Revolution](https://opensea.io/collection/devs-for-revolution) NFT.
```suggestion
The DAO operates inside our [Discord]. To gain access to this server you need to own a [Devs for Revolution](https://opensea.io/collection/devs-for-revolution) NFT. You can find the contract for purchasing one [here](https://etherscan.io/token/0x25ed58c027921e14d86380ea2646e3a1b5c55a8b) and a good how to article on how to purchase one from @jkup, [here](https://jonkuperman.com/how-to-join-developer-dao/ ). 
```

2021-09-10 15:57 UTC, with-heart commented on README.md
> +[![Chat on Discord](https://img.shields.io/badge/chat-Discord-7289DA?logo=discord)](https://discord.com/invite/ZHZup79J) [![Follow on Twitter](https://img.shields.io/badge/social-Twitter-1DA1F2?logo=
```suggestion
[![Chat on Discord](https://img.shields.io/badge/chat-Discord-7289DA?logo=discord)][Discord] [![Follow on Twitter](https://img.shields.io/badge/social-Twitter-1DA1F2?logo=twitter)](https://twitter.com/developer_dao) [![See on Etherscan](https://img.shields.io/badge/MintNFT-Ethereum-3C3C3D?logo=ethereum)](https://etherscan.io/token/0x25ed58c027921e14d86380ea2646e3a1b5c55a8b#writeContract)
```

2021-09-10 17:16 UTC, Dhaiwat10 commented on README.md
> +[![Chat on Discord](https://img.shields.io/badge/chat-Discord-7289DA?logo=discord)](https://discord.com/invite/ZHZup79J) [![Follow on Twitter](https://img.shields.io/badge/social-Twitter-1DA1F2?logo=
> I wonder if we have enough members yet to qualify for a custom Discord invite URL. I'm not even sure who to ask!

This might help: https://support.discord.com/hc/en-us/articles/115001542132-Server-Vanity-URLs

2021-09-10 17:20 UTC, Dhaiwat10 commented on README.md
> +That said, there is a limited supply of NFT's that can be created.
> This is probably a great place to link to one of those tools that shows the remaining available NFTs. Not sure which one we should link to though, I think I've seen a few.

This one helped me the most:  http://ddao.ibby.dev/

2021-09-10 20:30 UTC, kempsterrrr commented on README.md
> +[![Chat on Discord](https://img.shields.io/badge/chat-Discord-7289DA?logo=discord)](https://discord.com/invite/ZHZup79J) [![Follow on Twitter](https://img.shields.io/badge/social-Twitter-1DA1F2?logo=
Looks like we need sever boosting so no can do atm :(

2021-09-10 20:33 UTC, kempsterrrr commented on README.md
> +As stated on : "Developers around the world are tired of working and contributing their time and effort to enrich the top 1%. Join the movement that is community owned, building the future from the b
This was stated in the contract code. Mentioned in #11 that reading it back didn't really fit so happy to remove. Sure we can work on the text later.

2021-09-10 20:48 UTC, kempsterrrr commented
Forgive me for all those commit messages 🤦🏻‍♂️ I'd not worked this way before. Is there to undo and batch or squash to clean up the commit history?

2021-09-10 20:49 UTC, Dhaiwat10 commented
> Forgive me for all those commit messages 🤦🏻‍♂️ I'd not worked this way before. Is there to undo and batch or squash to clean up the commit history?

We can do a _squash and merge_ when merging the PR :)

2021-09-10 21:01 UTC, Dhaiwat10 requested changes

2021-09-10 21:08 UTC, kempsterrrr commented on README.md
> +The DAO operates inside our [discord sever](https://twitter.com/dabit3). To gain access to this server you need to own a [Devs for Revolution](https://opensea.io/collection/devs-for-revolution) NFT.
Good spot. Fixed in latest push

2021-09-10 21:09 UTC, kempsterrrr commented on README.md
> +That said, there is a limited supply of NFT's that can be created.
Add 👍🏻

2021-09-10 21:18 UTC, kempsterrrr commented
All changes and additions should be included now, thanks for bearing with me. Glad we can squash all those commits 😂

2021-09-10 21:43 UTC, Dhaiwat10 approved these changes
LGTM!

2021-09-11 03:21 UTC, thomasmetta approved these changes

2021-09-11 08:02 UTC, merged