Features/design proposal 2021 09 11
Developer-DAO/developer-dao pull request #41
Opened 2021-09-12 23:44 UTC by codingwithmanny

**Context:**
Fixes #20

**Dependency:**
Waiting for PR #40 to merge as this relies on it.

**Before:**
![localhost_3000_ (1)](https://user-images.githubusercontent.com/318082/133006516-c198a200-3ba3-4900-90f9-ad345d00a6e2.png)

**Proposal:**
![localhost_3000_](https://user-images.githubusercontent.com/318082/133006487-3aae88a4-79bc-47e2-9cf6-d5c7e4d9ad5b.png)

2021-09-13 07:31 UTC, with-heart approved these changes
This looks great! It's definitely a nice improvement to the UI.

2021-09-13 07:31 UTC, with-heart commented on src/locales/fr/translations.js
> +  enterDeveloperId: 'Veuillez remplir le champ avec un id DAO du développeur',
@Canopix I'm not super familiar with `i18next`. Have some questions for you since you did the initial PR! No worries if you don't have answers, just wanted to check with you :)

- What happens when a translation is missing? Like in this case, we don't have a definition for `es`.
- Do you have any suggestions for how to best handle missing translations? I imagine things will be moving pretty quickly soon enough—wondering if you have any ideas for how to build a process for keeping up with needed translations.

2021-09-13 07:31 UTC, with-heart commented on tailwind.config.js
> +      sans: ['"Inter"', 'sans-serif'],
Wondering if we should expand this to use `system-ui` as a fallback between Internet and `sans-serif`.

2021-09-13 10:11 UTC, codingwithmanny commented on src/locales/fr/translations.js
> +  enterDeveloperId: 'Veuillez remplir le champ avec un id DAO du développeur',
@with-heart this should help clarify things.

**File:** `src/i18n.js`

```js
const fallbackLng = ['en'];
```

but looks like I forgot to add `fr` in `availableLanguages`

2021-09-13 10:14 UTC, codingwithmanny commented on src/components/Icons/index.js
> +};
Done.

2021-09-13 10:14 UTC, codingwithmanny commented on src/locales/fr/translations.js
> +  enterDeveloperId: 'Veuillez remplir le champ avec un id DAO du développeur',
Done.

2021-09-13 10:14 UTC, codingwithmanny commented on tailwind.config.js
> +      sans: ['"Inter"', 'sans-serif'],
Done.

2021-09-13 10:30 UTC, codingwithmanny commented
Conflicts resolved although I'm proposing we remove the translation `Hosting is` based on conversation mentioned here:
https://github.com/Developer-DAO/developer-dao/pull/39#issuecomment-918051709

Just need to confirm if it's alright with everyone.

**Proposed:**
![localhost_3000_ (2)](https://user-images.githubusercontent.com/318082/133068655-53445877-1990-4b9b-b55c-937edeea0675.png)

2021-09-13 17:07 UTC, with-heart commented on tailwind.config.js
> +      sans: ['"Inter"', 'sans-serif'],
lmao Internet font 😆

2021-09-13 17:08 UTC, with-heart commented
@codingwithmanny Go for it!

2021-09-14 04:28 UTC, with-heart commented on src/App.js
> +      {nft.owner || null ? (
Do we need the `|| null` here?

2021-09-14 04:32 UTC, with-heart requested changes

2021-09-14 04:32 UTC, with-heart commented on src/App.js
> -      </h5>
I think one of the things that needs to be rebased is the Vercel sponsorship part of the footer. Mind getting that @codingwithmanny?

2021-09-14 08:08 UTC, codingwithmanny commented on src/App.js
> +      {nft.owner || null ? (
Yeah it's weird. I tried doing the if statement on `nft.owner` and even if there is no owner it still returns a value, which is weird. I'm going to look at this again.

2021-09-14 08:51 UTC, codingwithmanny commented on src/App.js
> +      {nft.owner || null ? (
Fixed.

2021-09-14 08:53 UTC, codingwithmanny commented on src/App.js
> -      </h5>
I changed it slightly, so looking for feedback if that works, and pending confirmation on translations.

`en`
```
Hosting by:
```

`fr`
```
Hébergement web par : // Web hosting by:
```

`es`
```
Alojamiento web por:' // Web hosting by:
```

<img width="2032" alt="Screen Shot 2021-09-14 at 4 50 22 AM" src="https://user-images.githubusercontent.com/318082/133227250-156f5d89-d6b3-4536-b596-010155c7898b.png">

2021-09-14 13:50 UTC, with-heart commented on src/App.js
> -      </h5>
I think that looks great! Maybe a little extra space between the "Made by"+social icons and the "Hosting by" section? Whatever feels right to you

2021-09-14 13:53 UTC, merged

2021-09-15 02:35 UTC, thomasmetta commented on src/App.js
> -      </h5>
@codingwithmanny looks good, better than my incline design haha