feat: add 'copy link to nft' button
Developer-DAO/developer-dao pull request #79
Opened 2021-09-16 18:48 UTC by Dhaiwat10

I added [Chakra UI's package for icons](https://chakra-ui.com/docs/media-and-icons/icon) too since I think we'll need to use these icons in the future as the project grows.

2021-09-17 02:33 UTC, with-heart requested changes
Looks great! Just a few small suggestions!

2021-09-17 02:33 UTC, with-heart commented on src/pages/index.js
> +        </Button>
`Button` has a `leftIcon` prop that makes this nice and easy :)

```suggestion
        <Button onClick={() => copyLinkToNFT(props.developerId)} leftIcon={<LinkIcon />}>
          Copy link to this NFT
        </Button>
```

2021-09-17 02:33 UTC, with-heart commented on src/pages/index.js
> +  alert('Link copied!');
Chakra has a `useToast` hook that would be great for this! https://codesandbox.io/s/busy-wiles-bpjvw

2021-09-17 04:05 UTC, narbs91 commented on src/pages/index.js
> +          &nbsp;Copy link to this NFT
Should we introduce a i18n folder with properties files to start adding static text entries to for translation?  Basically we should avoid having static text like and instead have these all stored in one central place.   Don't know what the rest of the gang thinks here?

2021-09-17 13:29 UTC, with-heart commented on src/pages/index.js
> +          &nbsp;Copy link to this NFT
Oh, good catch @narbs91. We already have that, forgot about it for a minute 😅

2021-09-17 15:11 UTC, Dhaiwat10 commented on src/pages/index.js
> +          &nbsp;Copy link to this NFT
Good catch! I removed the static text & added the text to the translation file for English. What do we do about the rest of the languages, though? 🤔

2021-09-17 15:17 UTC, with-heart approved these changes
This looks great! I left some feedback on the use of `toast` but it's just a suggestion and we can merge if we'd prefer to stick with what you've got!

2021-09-17 15:17 UTC, with-heart commented on src/pages/index.js
> +      duration: 5000,
imo we shouldn't pass these options and just let the toast use the defaults: 

- `status` of `info`
	- `success` is imo more for like hitting an API or things of more significant importance than copying some text to the clipboard
- `duration` of `3000` 
	- 5 seconds is a long time just to tell someone that we copied some text to the clipboard
	- 3 seconds is also a long time, but at least it's less than 5 lol

2021-09-17 15:23 UTC, with-heart commented on src/pages/index.js
> +          &nbsp;Copy link to this NFT
I'm still unsure what an effective process for handling missing translations looks like. 

I don't think it's worth slowing down the dev cycle because of missing translations this early in the project's life, so for now we can just create a corresponding issue to add the missing translations (with [a task list](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists) of the missing languages) and leave it to translators to catch up. 

I'll create an issue template for that so we can make it semi-automated.

2021-09-17 15:28 UTC, Dhaiwat10 commented on src/pages/index.js
> +      duration: 5000,
Done!

2021-09-17 20:55 UTC, narbs91 commented on src/pages/index.js
> +          &nbsp;Copy link to this NFT
Yeah, it's pretty much going to come down to getting people to translate the texts as the file grows with the project.  Those can probably be flushed out periodically as we move along via separate PR's

2021-09-17 21:01 UTC, narbs91 commented
Looks awesome overall @Dhaiwat10 , great stuff!  One thing i did notice is when you cross the mobile breakpoint from desktop the text doesn't dynamically shift in size too to match the etherscan and opensea links:

Desktop:

![image](https://user-images.githubusercontent.com/29411347/133853069-0f9d1a5c-47e7-407e-80ba-34e038688736.png)

Mobile:

![image](https://user-images.githubusercontent.com/29411347/133853108-e6479744-fd84-4461-8a45-2dc3ce03c5f6.png)


Is this by design perhaps?

2021-09-17 21:02 UTC, narbs91 commented
Hmm looks like the screenshots didn't serve too much use, but you can notice it if you open the dev tools and dynamically resize the window

2021-09-17 21:42 UTC, narbs91 requested changes

2021-09-17 21:42 UTC, narbs91 commented on src/pages/index.js
> +      `https://developerdao.com/?id=${props.developerId}`,
Actually @Dhaiwat10 can you put this link prefix `https://developerdao.com` in the DeveloperDaoConstants file?

2021-09-17 22:44 UTC, Dhaiwat10 commented on src/pages/index.js
> +      `https://developerdao.com/?id=${props.developerId}`,
> Looks awesome overall @Dhaiwat10 , great stuff! One thing i did notice is when you cross the mobile breakpoint from desktop the text doesn't dynamically shift in size too to match the etherscan and opensea links:
> 
> Desktop:
> 
> ![image](https://user-images.githubusercontent.com/29411347/133853069-0f9d1a5c-47e7-407e-80ba-34e038688736.png)
> 
> Mobile:
> 
> ![image](https://user-images.githubusercontent.com/29411347/133853108-e6479744-fd84-4461-8a45-2dc3ce03c5f6.png)
> 
> Is this by design perhaps?

Yeah, it's _kind of_ by design. The text size for the owner box was reduced to allow the long address to fit on mobile screens.

2021-09-17 22:44 UTC, Dhaiwat10 commented on src/pages/index.js
> +      `https://developerdao.com/?id=${props.developerId}`,
> Actually @Dhaiwat10 can you put this link prefix `https://developerdao.com` in the DeveloperDaoConstants file?

Sure thing! Thanks for suggesting this

2021-09-17 23:42 UTC, Dhaiwat10 commented
Removed some unused imports, too. Let me know if everything is in order

2021-09-17 23:45 UTC, narbs91 approved these changes
Looks good to me 👍

2021-09-18 02:43 UTC, with-heart approved these changes
LGTM!

2021-09-19 02:18 UTC, merged