Feature/add direct nft link
Developer-DAO/developer-dao pull request #80
Opened 2021-09-16 19:22 UTC by narbs91

Issue: #67

2021-09-16 19:59 UTC, fmoliveira reviewed
Great work on extracting the constants into a new file, I really liked that!

It all looks good to me, but I will leave the approval part for the assigned reviewers. I'm leaving a small nitpicky comment that could improve readability (in my opinion). It's optional and totally up to you to do or to not do!

Well done, @narbs91 !

![](https://media1.giphy.com/media/tCV2LrPPYfqCY/giphy.gif)

2021-09-16 19:59 UTC, fmoliveira commented on src/components/Search/Dev/DevName.js
> +        <h1 className="font-semibold mb-2">{nft.name}</h1>
For a bit more concise code, I'd suggest returning this default early instead of using a ternary. I think it would read slightly easier. Just a personal opinion, though. 😃 

It would look like:

```js
function DevName({ nft, developerId }) {
  if (!nft.owner) {
    return <h1>...</h1>
  }
  
  return <Button...>...</Button>
}
```

2021-09-16 20:02 UTC, narbs91 commented on src/components/Search/Dev/DevName.js
> +        <h1 className="font-semibold mb-2">{nft.name}</h1>
Thanks for the review @fmoliveira !  Sounds good to me, i'll make that tweak later on today

2021-09-16 20:07 UTC, fmoliveira commented
One other thing, what do you think about making the OpenSea button have the same height as the Etherscan button, for consistency? Maybe reduce the OpenSea icon a little bit? I'm not sure if reducing it would look aesthetically good, though 🤔

2021-09-16 20:49 UTC, codingwithmanny commented
I might want to propose something here and @narbs91 you tell me what you think.

<img width="804" alt="Screen Shot 2021-09-16 at 4 48 15 PM" src="https://user-images.githubusercontent.com/318082/133683671-0dc0503e-e358-4c06-acbf-cfec59766873.png">

2021-09-16 21:16 UTC, narbs91 commented
> One other thing, what do you think about making the OpenSea button have the same height as the Etherscan button, for consistency? Maybe reduce the OpenSea icon a little bit? I'm not sure if reducing it would look aesthetically good, though 🤔

I'll have a play around with the styling to see how it looks but yeah it might just be a matter of shrinking the icon a tad

2021-09-16 21:20 UTC, narbs91 commented
> I might want to propose something here and @narbs91 you tell me what you think.
> 
> <img alt="Screen Shot 2021-09-16 at 4 48 15 PM" width="804" src="https://user-images.githubusercontent.com/318082/133683671-0dc0503e-e358-4c06-acbf-cfec59766873.png">

I think the unclaimed button is a great idea but i think it should actually be something for #77 no?  Since that button would suggest the NFT available and link off to the contract for minting when pressed.  I'm not so hot for the hover as the blues seem to be colliding a bit don't you think?

2021-09-16 21:35 UTC, codingwithmanny commented
@narbs91 I'm good with no blue hover.
For #{77} that still needs to be flushed out, so for the unclaimed, I'm also ok with just just a button (really a span) with no hover or checkmark but fits the same size as the button.
Icon should be 24px h+w for the button and padding / position of icon I think should be left aligned a bit more.

2021-09-16 21:38 UTC, with-heart commented
@fmoliveira Everyone is welcome to review a PR!

2021-09-16 22:27 UTC, codingwithmanny approved these changes
LGTM

2021-09-17 00:10 UTC, nheingit requested changes
All of this looks super, thanks for this!

Only change is the `src/utils/DeveloperDaoContstants.js` where "Contstants" is misspelled.

2021-09-17 01:41 UTC, narbs91 commented
> All of this looks super, thanks for this!
> 
> Only change is the `src/utils/DeveloperDaoContstants.js` where "Contstants" is misspelled.

Doh! Good catch, i'll fix that up real quick

2021-09-17 02:15 UTC, with-heart approved these changes
Looks great! Nicely done!

2021-09-17 02:16 UTC, merged